# Generated by Django 3.1.5 on 2021-04-05 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReleasesApp', '0002_auto_20210330_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='averagescore',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='release',
            name='hottestvalue',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
